services:
  web:
    depends_on:
      - builder
    build: nginx/.
    ports:
      - "443:443"
    volumes:
      - html:/usr/share/nginx
      - certificates:/etc/ssl/rahti
  
  builder:
    build: src/.
    environment:
      CLUSTER_ENV_VERSION: "Openshift 4.15 / Kubernetes 1.28"
      SERVICE_DOCS_URL: "https://docs.csc.fi/cloud/rahti2/"
      CLUSTER_LOGIN_URL_OIDCIDP: "https://console-openshift-console.apps.2.rahti.csc.fi/dashboards"
    volumes:
      - html:/usr/share/nginx

volumes:
  html:
  certificates:
    