services:
  web:
    depends_on:
      - builder
    build: nginx/.
    ports:
      - "443:443"
    volumes:
      - html:/usr/share/nginx
      - certificates:/etc/ssl/rahti
  
  builder:
    build: src/.
    volumes:
      - html:/usr/share/nginx

volumes:
  html:
  certificates:
    